### ISSUE TITLE
Reverse Proxy Load Testing

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#596]
## Description

In an effort to make sure we understand the impact of the reverse proxy fallback to content build from next build we need to properly test the response times before and after our changes are applied.
This will require load testing to https://dev.va.gov with rev proxy changes enabled and disabled.

## Test Case
The following test case needs to be done with both reverse proxy changes off and on.
Using Locust and the included code, load test https://dev.va.gov.
Start the test with a ramp up to 500 users. 
After 500 users have been reached, allow the test to continue running an additional 15 mins.
After the additional 15 minute wait add another 500 concurrent users.
When you have a total of 1000 users wait another 15 mins with the test still active.
After the additional 15 minute wait add another 500 concurrent users.
Once you have a total of 1500 users, allow the test to run for another 15 minutes.
Download the reports and attach them to this ticket.

## Code
<details>
<summary>locustfile.py</summary>

`
from locust import HttpUser, task, between
import random
class VAGOV(HttpUser):
    wait_time = between(1, 5)

    @task
    def va_gov(self):
        list_of_urls = ['/wilmington-health-care',
        '/wilmington-health-care/about-us',
        '/wilmington-health-care/about-us/history',
        '/wilmington-health-care/about-us/leadership',
        '/wilmington-health-care/about-us/mission-and-vision',
        '/wilmington-health-care/about-us/mission-and-vision/diversity-and-inclusion',
        '/wilmington-health-care/about-us/performance',
        '/wilmington-health-care/billing-and-insurance',
        '/wilmington-health-care/chaplain-services',
        '/wilmington-health-care/contact-us',
        '/wilmington-health-care/dav-vans-transportation-for-veterans',
        '/wilmington-health-care/events',
        '/wilmington-health-care/events/43663',
        '/wilmington-health-care/events/43774',
        '/wilmington-health-care/events/44258',
        '/wilmington-health-care/events/44899',
        '/wilmington-health-care/events/45058',
        '/wilmington-health-care/events/45192',
        '/wilmington-health-care/events/47303',
        '/wilmington-health-care/events/47326',
        '/wilmington-health-care/events/48069',
        '/wilmington-health-care/events/49369',
        '/wilmington-health-care/events/49510',
        '/wilmington-health-care/events/49614',
        '/wilmington-health-care/events/49989',
        '/wilmington-health-care/events/50690',
        '/wilmington-health-care/events/51053',
        '/wilmington-health-care/events/51975',
        '/wilmington-health-care/events/51976',
        '/wilmington-health-care/events/52298',
        '/wilmington-health-care/events/52506',
        '/wilmington-health-care/events/53279',
        '/wilmington-health-care/events/53338',
        '/wilmington-health-care/events/53350',
        '/wilmington-health-care/events/53353',
        '/wilmington-health-care/events/53364',
        '/wilmington-health-care/events/53760',
        '/wilmington-health-care/events/54105',
        '/wilmington-health-care/events/54158',
        '/wilmington-health-care/events/54159',
        '/wilmington-health-care/events/54162',
        '/wilmington-health-care/events/54163',
        '/wilmington-health-care/events/54968',
        '/wilmington-health-care/events/56791',
        '/wilmington-health-care/events/56801',
        '/wilmington-health-care/events/56802',
        '/wilmington-health-care/events/56803',
        '/wilmington-health-care/events/56804',
        '/wilmington-health-care/events/57099',
        '/wilmington-health-care/events/57509',
        '/wilmington-health-care/events/57603',
        '/wilmington-health-care/events/57819',
        '/wilmington-health-care/events/57821',
        '/wilmington-health-care/events/60841',
        '/wilmington-health-care/events/60843',
        '/wilmington-health-care/events/61112',
        '/wilmington-health-care/events/61114',
        '/wilmington-health-care/events/61116',
        '/wilmington-health-care/events/61117',
        '/wilmington-health-care/events/61748',
        '/wilmington-health-care/events/62571',
        '/wilmington-health-care/events/62572',
        '/wilmington-health-care/events/62925',
        '/wilmington-health-care/events/62926',
        '/wilmington-health-care/events/63167',
        '/wilmington-health-care/events/63393',
        '/wilmington-health-care/events/63647',
        '/wilmington-health-care/events/64741',
        '/wilmington-health-care/events/64934',
        '/wilmington-health-care/events/65187',
        '/wilmington-health-care/events/66004',
        '/wilmington-health-care/events/66026',
        '/wilmington-health-care/events/66615',
        '/wilmington-health-care/events/66616',
        '/wilmington-health-care/events/66618',
        '/wilmington-health-care/events/66641',
        '/wilmington-health-care/events/66642',
        '/wilmington-health-care/events/66643',
        '/wilmington-health-care/events/66644',
        '/wilmington-health-care/events/66645',
        '/wilmington-health-care/events/66646',
        '/wilmington-health-care/events/66730',
        '/wilmington-health-care/events/66731',
        '/wilmington-health-care/events/66732',
        '/wilmington-health-care/events/66733',
        '/wilmington-health-care/events/66734',
        '/wilmington-health-care/events/66735',
        '/wilmington-health-care/events/67529',
        '/wilmington-health-care/events/67795',
        '/wilmington-health-care/events/68309',
        '/wilmington-health-care/events/68310',
        '/wilmington-health-care/events/69125',
        '/wilmington-health-care/events/69220',
        '/wilmington-health-care/events/69221',
        '/wilmington-health-care/events/69745',
        '/wilmington-health-care/events/70349',
        '/wilmington-health-care/events/70350',
        '/wilmington-health-care/events/past-events',
        '/wilmington-health-care/events/past-events/page-2',
        '/wilmington-health-care/events/past-events/page-3',
        '/wilmington-health-care/events/past-events/page-4',
        '/wilmington-health-care/events/past-events/page-5',
        '/wilmington-health-care/events/past-events/page-6',
        '/wilmington-health-care/events/past-events/page-7',
        '/wilmington-health-care/events/past-events/page-8',
        '/wilmington-health-care/events/past-events/page-9',
        '/wilmington-health-care/health-services',
        '/wilmington-health-care/health-services/caregiver-support',
        '/wilmington-health-care/health-services/homeless-veteran-care',
        '/wilmington-health-care/health-services/lgbtq-veteran-care',
        '/wilmington-health-care/health-services/mental-health-care',
        '/wilmington-health-care/health-services/minority-veteran-care',
        '/wilmington-health-care/health-services/patient-advocates',
        '/wilmington-health-care/health-services/returning-service-member-care',
        '/wilmington-health-care/health-services/suicide-prevention',
        '/wilmington-health-care/health-services/women-veteran-care',
        '/wilmington-health-care/locations',
        '/wilmington-health-care/locations/atlantic-county-va-clinic',
        '/wilmington-health-care/locations/cape-may-county-va-clinic',
        '/wilmington-health-care/locations/cumberland-county-va-clinic',
        '/wilmington-health-care/locations/kent-county-va-clinic',
        '/wilmington-health-care/locations/sussex-county-va-clinic',
        '/wilmington-health-care/locations/wilmington-va-medical-center',
        '/wilmington-health-care/locations/wilmington-va-medical-center/campus-map',
        '/wilmington-health-care/locations/wilmington-va-mobile-clinic',
        '/wilmington-health-care/make-an-appointment',
        '/wilmington-health-care/medical-records-office',
        '/wilmington-health-care/news-releases',
        '/wilmington-health-care/news-releases/2018-visn-4-annual-report',
        '/wilmington-health-care/news-releases/2020-military-veterans-mental-health-summit',
        '/wilmington-health-care/news-releases/400000-veterans-enrolled-in-va-health-care-over-past-365-days-30-increase-over-last-year',
        '/wilmington-health-care/news-releases/all-veterans-and-families-invited-to-a-one-stop-virtual-resource-event',
        '/wilmington-health-care/news-releases/all-wwii-veterans-are-now-eligible-for-va-health-care',
        '/wilmington-health-care/news-releases/at-the-direction-of-president-biden-va-is-expanding-health-care-eligibility-to-millions-of-veterans',
        '/wilmington-health-care/news-releases/covid-19-vaccinations-for-eligible-veterans-75-years-and-older-at-blue-hen-mall-on-jan-31-0',
        '/wilmington-health-care/news-releases/covid-19-vaccinations-for-eligible-veterans-75-years-and-older-at-blue-hen-mall-on-jan-31',
        '/wilmington-health-care/news-releases/covid-19-vaccinations-for-eligible-veterans-75-years-and-older-at-cape-may-county-veterans-clinic-on-jan-30',
        '/wilmington-health-care/news-releases/dover-based-va-outpatient-clinic-to-relocate-expand-services-in-2020',
        '/wilmington-health-care/news-releases/end-veteran-suicide-keep-our-veterans-alive',
        '/wilmington-health-care/news-releases/ending-veteran-homelessness-increasing-access-to-affordable-housing',
        '/wilmington-health-care/news-releases/flag-instillation-to-honor-veterans-who-died-from-suicide',
        '/wilmington-health-care/news-releases/home-press-room-va-announces-expansion-of-close-to-me-cancer-program-as-part-of-the-cancer-moonshot',
        '/wilmington-health-care/news-releases/jeffrey-beiler-ii-named-acting-wilmington-va-medical-center-director',
        '/wilmington-health-care/news-releases/more-than-50000-women-veterans-enrolled-in-va-health-care-over-past-365-days-marking-the-largest-enrollment-year',
        '/wilmington-health-care/news-releases/pact-act-expansion',
        '/wilmington-health-care/news-releases/page-10',
        '/wilmington-health-care/news-releases/page-2',
        '/wilmington-health-care/news-releases/page-3',
        '/wilmington-health-care/news-releases/page-4',
        '/wilmington-health-care/news-releases/page-5',
        '/wilmington-health-care/news-releases/page-6',
        '/wilmington-health-care/news-releases/page-7',
        '/wilmington-health-care/news-releases/page-8',
        '/wilmington-health-care/news-releases/page-9',
        '/wilmington-health-care/news-releases/physical-therapy-opens-in-cape-may-veterans-clinic',
        '/wilmington-health-care/news-releases/relocation-and-expansion-of-cape-may-county-va-outpatient-clinic',
        '/wilmington-health-care/news-releases/safe-mental-health-care-during-the-covid-19-outbreak',
        '/wilmington-health-care/news-releases/south-jersey-vet-center-ribbon-cutting-ceremony-set-for-june-22',
        '/wilmington-health-care/news-releases/the-next-pact-act-deadline-health-care-enrollment-for-veterans-who-deployed-to-combat-zones',
        '/wilmington-health-care/news-releases/through-2027-veterans-no-longer-need-to-pay-copays-for-their-first-three-outpatient-mental-health-care-visits-of',
        '/wilmington-health-care/news-releases/trust-in-va-among-veteran-patients-rises-to-918-up-6-since-2018',
        '/wilmington-health-care/news-releases/va-and-law-enforcement-collaboration-leads-to-increase-in-health-care-utilization-study-finds',
        '/wilmington-health-care/news-releases/va-announces-2024-equity-action-plan-new-actions-to-ensure-that-all-veterans-receive-the-health-care-and',
        '/wilmington-health-care/news-releases/va-announces-5m-in-grant-funding-for-transitional-supportive-housing-for-homeless-veterans',
        '/wilmington-health-care/news-releases/va-announces-goal-to-house-41000-veterans-experiencing-homelessness-in-2024',
        '/wilmington-health-care/news-releases/va-announces-new-program-to-help-more-than-40000-veterans-stay-in-their-homes',
        '/wilmington-health-care/news-releases/va-announces-updates-to-help-veterans-using-va-home-loan-benefits-remain-competitive-in-the-housing-market',
        '/wilmington-health-care/news-releases/va-expands-access-to-care-and-benefits-for-some-former-service-members-who-did-not-receive-an-honorable-or',
        '/wilmington-health-care/news-releases/va-expands-in-vitro-fertilization-for-veterans',
        '/wilmington-health-care/news-releases/va-extends-presumptions-of-service-connection-for-three-new-cancer-types',
        '/wilmington-health-care/news-releases/va-has-screened-5-million-veterans-for-toxic-exposures-paving-the-way-for-early-detection-and-treatment-of',
        '/wilmington-health-care/news-releases/va-healthcare-visn-4-announces-new-medical-center-director',
        '/wilmington-health-care/news-releases/va-housed-more-than-46000-homeless-veterans-in-2023',
        '/wilmington-health-care/news-releases/va-improves-access-to-care-reduces-wait-times-for-new-patient-appointments-in-primary-and-mental-health-care',
        '/wilmington-health-care/news-releases/va-launches-new-surgery-initiative-across-the-nation-a-critical-step-to-saving-the-lives-of-veterans-considering',
        '/wilmington-health-care/news-releases/va-makes-historic-commitments-to-hire-and-support-military-spouses',
        '/wilmington-health-care/news-releases/va-offers-new-urgent-care-benefit-for-enrolled-veterans',
        '/wilmington-health-care/news-releases/va-on-track-to-house-38000-homeless-veterans-in-2023-awards-1b-in-grants-to-help-homeless-and-at-risk-veterans',
        '/wilmington-health-care/news-releases/va-proposes-rule-to-extend-presumed-areas-of-exposure-to-agent-orange-and-other-herbicides',
        '/wilmington-health-care/news-releases/va-provides-free-emergency-suicide-prevention-care-to-nearly-50000-veterans-and-former-service-members-in-first',
        '/wilmington-health-care/news-releases/va-provides-veterans-fleeing-domestic-violence-with-housing-and-supportive-services',
        '/wilmington-health-care/news-releases/va-to-award-1m-grant-to-fight-homelessness-and-improve-transitional-housing-in-delaware',
        '/wilmington-health-care/news-releases/va-to-award-525-million-in-grants-to-local-organizations-working-to-prevent-veteran-suicide',
        '/wilmington-health-care/news-releases/va-to-award-four-grants-to-local-organizations-to-help-prevent-and-end-veteran-homelessness-in-delaware-and',
        '/wilmington-health-care/news-releases/va-to-host-veteran-town-hall-and-provide-resources',
        '/wilmington-health-care/news-releases/va-to-host-veteran-town-hall-in-southern-delaware',
        '/wilmington-health-care/news-releases/va-to-host-veteran-town-hall-in-southern-nj',
        '/wilmington-health-care/news-releases/va-to-host-women-veterans-health-summit',
        '/wilmington-health-care/news-releases/veteran-family-fun-day-and-claims-clinic-0',
        '/wilmington-health-care/news-releases/veteran-family-fun-day-and-claims-clinic',
        '/wilmington-health-care/news-releases/veteran-trust-in-va-has-increased-25-since-2016-reaches-all-time-high',
        '/wilmington-health-care/news-releases/veterans-affairs-and-community-partners-to-highlight-veteran-suicide-prevention-efforts-in-southern-new-jersey',
        '/wilmington-health-care/news-releases/veterans-affairs-expands-health-care-services-to-veterans-in-kent-county-with-opening-of-new-clinic',
        '/wilmington-health-care/news-releases/veterans-affairs-sending-50-nurses-to-southern-nj-nursing-homes-to-support',
        '/wilmington-health-care/news-releases/veterans-affairs-to-hold-vaccination-event-april-10-at-va-clinic-in-northfield',
        '/wilmington-health-care/news-releases/veterans-affairs-to-hold-vaccination-events-this-weekend-at-va-clinics-in-kent-and-sussex-counties',
        '/wilmington-health-care/news-releases/vha-transitions-to-covid-19-future-state-by-implementing-health-protection-levels-to-enhance-safety-of-veterans',
        '/wilmington-health-care/news-releases/visin-4-2019-annual-report',
        '/wilmington-health-care/news-releases/visn4-2020-annual-report',
        '/wilmington-health-care/news-releases/vsin-4-2019-annual-report',
        '/wilmington-health-care/news-releases/wall-of-honor-nominations-being-accepted-for-southern-new-jersey',
        '/wilmington-health-care/news-releases/wall-of-honor-nominations-being-accepted-in-delaware',
        '/wilmington-health-care/news-releases/wilmington-va-expands-dialysis-care',
        '/wilmington-health-care/news-releases/wilmington-va-expands-long-term-care-options-for-new-jersey-veterans',
        '/wilmington-health-care/news-releases/wilmington-va-hosts-virtual-veteran-town-hall',
        '/wilmington-health-care/news-releases/wilmington-va-launches-wilmington-va-hiring-week-to-recruit-local-talent-in-delaware-and-southern-new-jersey',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-2020-annual-report',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-begins-janssen-covid-19-vaccinations',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-covid-19-vaccination-eligibility-criteria-expanded',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-dialysis-receives-national-ratings',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-encourages-delaware-and-southern-new-jersey-landlords-to-advocate-for-homeless',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-expands-covid-19-vaccinations-to-adolescents-under-save-lives-act',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-expands-offering-of-covid-19-booster-shots',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-readies-to-begin-offering-covid-19-booster-shots',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-surpasses-8000-telehealthvirtual-visits-in-fiscal-year-2020',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-to-begin-covid-19-vaccine-distribution-with-moderna-at-its-outpatient-clinics-in',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-to-begin-covid-19-vaccine-distribution-with-moderna',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-to-expand-veteran-health-care-services-in-atlantic-county',
        '/wilmington-health-care/news-releases/wilmington-va-medical-center-to-hold-covid-19-vaccination-event-for-veterans-enrolled-in-va-health-care-march-27',
        '/wilmington-health-care/news-releases/wilmington-va-medical-centers-caregiver-support-program-is-scheduled-to-hold-its-second-annual-virtual-caregiver',
        '/wilmington-health-care/news-releases/wilmington-va-on-a-mission-to-roll-out-new-va-health-care-options',
        '/wilmington-health-care/news-releases/wilmington-va-police-earn-national-honors-to-be-recognized-may-21',
        '/wilmington-health-care/news-releases/wilmington-va-police-to-begin-to-use-body-cams-and-dash-cams',
        '/wilmington-health-care/news-releases/wilmington-va-recognizes-september-as-suicide-prevention-month',
        '/wilmington-health-care/news-releases/wilmington-va-teams-with-the-drug-enforcement-administration-for-national-prescription-drug-take-back-day',
        '/wilmington-health-care/news-releases/wilmington-va-to-host-resource-fair-town-hall-on-may-8',
        '/wilmington-health-care/news-releases/wilmington-va-to-host-women-and-lgbtq-veterans-resource-event',
        '/wilmington-health-care/news-releases/wilmington-vamc-center-announced-today-that-it-will-hold-a-virtual-listening-session-with-stakeholders',
        '/wilmington-health-care/news-releases/wilmington-veterans-affairs-medical-center-police-officer-receives-top-national-honor',
        '/wilmington-health-care/news-releases/wilmington-veterans-affairs-nursing-home-receives-5-star-rating',
        '/wilmington-health-care/news-releases/wvamc-welcomes-va-sec-delaware-delegation-and-veteran-leaders-for-annual-summit',
        '/wilmington-health-care/operating-status',
        '/wilmington-health-care/pharmacy',
        '/wilmington-health-care/policies',
        '/wilmington-health-care/programs',
        '/wilmington-health-care/programs/covid-19-vaccines',
        '/wilmington-health-care/programs/de-vet-help',
        '/wilmington-health-care/programs/va-health-chat',
        '/wilmington-health-care/register-for-care',
        '/wilmington-health-care/research',
        '/wilmington-health-care/research/research-and-development-resources',
        '/wilmington-health-care/staff-profiles/kibreab-gudeta',
        '/wilmington-health-care/staff-profiles/kim-butler',
        '/wilmington-health-care/staff-profiles/matthew-morris',
        '/wilmington-health-care/staff-profiles/pamela-ledeaux',
        '/wilmington-health-care/staff-profiles/vamsee-potluri',
        '/wilmington-health-care/status',
        '/wilmington-health-care/stories',
        '/wilmington-health-care/stories/atlantic-county-based-va-outpatient-clinic-to-relocate-expand-services-in-2023',
        '/wilmington-health-care/stories/battlefield-acupuncture-allows-veterans-to-use-alternative-medicine',
        '/wilmington-health-care/stories/beneficiary-travel-portal-instructional-videos',
        '/wilmington-health-care/stories/bonding-through-service-veteran-peers',
        '/wilmington-health-care/stories/changing-minds-vietnam-veteran-shares-his-experience-using-va-health-care',
        '/wilmington-health-care/stories/clc-veterans-stay-active-during-pandemic',
        '/wilmington-health-care/stories/covid-19-vaccine-eligibility-criteria-expanded',
        '/wilmington-health-care/stories/dont-delay-care-schedule-your-appointments',
        '/wilmington-health-care/stories/emergency-medical-care',
        '/wilmington-health-care/stories/empowering-veterans-one-sound-at-a-time-a-veterans-mission-to-support-fellow-comrades-with-hearing-aids',
        '/wilmington-health-care/stories/father-and-son-veterans-enjoy-a-holiday-visit-together-at-the-wilmington-va-community-living-center',
        '/wilmington-health-care/stories/feeding-the-soul',
        '/wilmington-health-care/stories/from-tragedy-to-triumph-va-employees-success-with-acupuncture-and-hands-on-medicine',
        '/wilmington-health-care/stories/haircuts-for-community-living-center-veterans',
        '/wilmington-health-care/stories/music-as-alternative-technique-to-healing',
        '/wilmington-health-care/stories/new-cape-may-county-cboc-to-open-dec-8',
        '/wilmington-health-care/stories/new-va-outpatient-clinic-in-dover-to-open-march-31',
        '/wilmington-health-care/stories/pact-act-march-story',
        '/wilmington-health-care/stories/page-2',
        '/wilmington-health-care/stories/page-3',
        '/wilmington-health-care/stories/page-4',
        '/wilmington-health-care/stories/page-5',
        '/wilmington-health-care/stories/page-6',
        '/wilmington-health-care/stories/patient-experience-msgt-frederick-montney-iii',
        '/wilmington-health-care/stories/quick-action-by-wilmington-va-police-saves-veteran-0',
        '/wilmington-health-care/stories/service-never-stops',
        '/wilmington-health-care/stories/spotlighting-social-work',
        '/wilmington-health-care/stories/spreading-the-word-on-va-connected-care',
        '/wilmington-health-care/stories/the-anonymous-responders',
        '/wilmington-health-care/stories/understanding-the-compact-act',
        '/wilmington-health-care/stories/uniting-for-heroes-the-southern-new-jersey-stand-down-supports-homeless-veterans',
        '/wilmington-health-care/stories/va-employee-honored-to-support-wheelchair-games',
        '/wilmington-health-care/stories/va-nurses-share-stories-about-fighting-covid-19',
        '/wilmington-health-care/stories/va-physician-receives-honorary-membership',
        '/wilmington-health-care/stories/va-police-team-earns-consecutive-national-honors',
        '/wilmington-health-care/stories/veteran-brings-home-gold-from-national-competition',
        '/wilmington-health-care/stories/veteran-drives-from-canada-to-receive-top-care-at-wilmington-va-medical-center',
        '/wilmington-health-care/stories/veteran-food-pantry',
        '/wilmington-health-care/stories/veteran-gets-medical-advice-with-va-health-chat',
        '/wilmington-health-care/stories/veteran-makes-a-life-changing-discovery-for-himself-and-shares-with-other-veterans',
        '/wilmington-health-care/stories/veteran-presents-flags-to-va-health-care-workers-0',
        '/wilmington-health-care/stories/veteran-received-second-to-none-care-at-wilmington-va-emergency-department',
        '/wilmington-health-care/stories/veteran-receives-universal-care-at-va',
        '/wilmington-health-care/stories/veteran-suicide-prevention-in-new-jersey',
        '/wilmington-health-care/stories/veterans-how-can-va-improve-your-health-care',
        '/wilmington-health-care/stories/veterans-in-long-term-care-stay-connected-and-active',
        '/wilmington-health-care/stories/veteransresponseteam',
        '/wilmington-health-care/stories/what-to-expect-as-we-move-forward',
        '/wilmington-health-care/stories/wilmington-community-shows-love-for-veterans',
        '/wilmington-health-care/stories/wilmington-staff-earn-national-recognition',
        '/wilmington-health-care/stories/wilmington-va-has-highest-drug-take-back-in-eastern-market',
        '/wilmington-health-care/stories/wilmington-va-hiring-week',
        '/wilmington-health-care/stories/wilmington-va-launches-state-of-the-art-dialysis-unit',
        '/wilmington-health-care/stories/wilmington-va-medical-center-2020-annual-report',
        '/wilmington-health-care/stories/wilmington-va-showcases-new-da-vinci-robot-and-endovascular-suite',
        '/wilmington-health-care/stories/wilmington-vamc-police-officer-receives-honor',
        '/wilmington-health-care/stories/wilmington-vamc-recognizes-volunteers',
        '/wilmington-health-care/stories/wvamc-police-train-stay-sharp-with-new-technology',
        '/wilmington-health-care/stories/wvamc-volunteer-is-governors-outstanding-volunteer-service-award-honoree',
        '/wilmington-health-care/va-police',
        '/wilmington-health-care/work-with-us',
        '/wilmington-health-care/work-with-us/internships-and-fellowships',
        '/wilmington-health-care/work-with-us/internships-and-fellowships/optometry',
        '/wilmington-health-care/work-with-us/internships-and-fellowships/optometry/ophthalmology-providers',
        '/wilmington-health-care/work-with-us/internships-and-fellowships/psychology-training-internship-program',
        '/wilmington-health-care/work-with-us/internships-and-fellowships/trainee-coordinators',
        '/wilmington-health-care/work-with-us/jobs-and-careers',
        '/wilmington-health-care/work-with-us/volunteer-or-donate']
        self.client.get(random.choice(list_of_urls))

    `
</details>

## Acceptance Criteria
Results should be added to this ticket.

Additional information supplied by Jeff

**Comment by mreed101** [comment]
Results with reverse proxy fallback from Next

[locust_dev_va_with_next_rev_proxy.pdf](https://github.com/user-attachments/files/16179684/locust_dev_va_with_next_rev_proxy.pdf)

Average response times 
1500 users = 1500ms
1000 users = 525ms
500 users = 384ms

**Comment by mreed101** [comment]
Testing results can be found at https://vfs.atlassian.net/wiki/spaces/AP1/pages/3304718546/Reverse+Proxy+load+testing+Results
On average there is roughly a .5 second difference in response time between content-build and next-build. Response times when user traffic is routed to next-build first via reverse proxy appear to be faster on average.
Our test leads us to believe that this is because nextjs(next-build) is more efficient when creating static pages than what we get from metalsmith(content-build).

**Comment by JeffKeeneVAGov** [comment]
Doesnt Metalsmith just build static files? Is it actually building files at runtime? I dont know if I agree with the conclusion. Can you elaborate? Are you saying the files themselves are better/smaller than the metalsmith files?

**Comment by nfpappas-oddball** [comment]
> Doesnt Metalsmith just build static files? Is it actually building files at runtime? I dont know if I agree with the conclusion. Can you elaborate? Are you saying the files themselves are better/smaller than the metalsmith files?

To elaborate, I believe that in nextbuild there is some optimization of the generated code. You can see that the file sizes for some of the events pages are smaller in next then they are in content build. 
![image](https://github.com/user-attachments/assets/d6896ffd-84b1-45e7-a1fa-f756c2fef3b2)

Both next and content build both generate static files but all static generators may not be equal. Smaller files in next could lead to the improved response times which is why I think we have better response times.

**Comment by JeffKeeneVAGov** [comment]
I agree that the files probably have been optimized. I am assuming the code splitting took place. I also assume that metal smith loads all js for every page vs the code splitting in nextjs. Could we get an analysis of the page loads using the lighthouse tool? I would like to advertise this improvement.

**Comment by mreed101** [comment]
Ticket created for lighthose testing https://github.com/department-of-veterans-affairs/next-build/issues/608

**Comment by mreed101** [comment]
Adding load testing results for staging
[report_next_build_staging_1722047823.103791.html.zip](https://github.com/user-attachments/files/16397912/report_next_build_staging_1722047823.103791.html.zip)

**Comment by nfpappas-oddball** [comment]
Adding load testing for staging 


[report_1722521548.6617193.zip](https://github.com/user-attachments/files/16457828/report_1722521548.6617193.zip)
