### ISSUE TITLE
[AP] Business Logic Documentation

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#615]
## Description
Next Build does not currently document any of it's underlining business logic for templates. 
The goal of this ticket is to identify known business logic that defers from content-build and document them in a unified space.

We need to create a business-logic.md file inside of the README directory that gives insights into the difference in functionality for:

- Timezones (Next Build shows dates based on the users local time)
- Registered Events (Events that have passed no longer show a register event button)

## Acceptance Criteria

- [ ] Business Logic is documented in the appropriate readme file

**Comment by ttran-Therisa** [comment]
relating [PR](https://github.com/department-of-veterans-affairs/next-build/pull/736)
