### ISSUE TITLE
[Bug] Next Build i18next loading

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#629]
## Description
VA components that use i18next fail to display their translated text when viewed on dev.va.gov.
Currently this issue can be seen with the <va-pagination> and <va-accordion> components.
This ticket is to identify and fix the cause of this issue.

The issue can be seen at https://dev.va.gov/outreach-and-events/events/

## Additional Context
i18next is used for internationalization. Translation data is stored via a key and the value of that key is passed to the component. Translations are stored in the component library in the [translation directory](https://github.com/department-of-veterans-affairs/component-library/tree/e3f65bbecea9f859839fc8071526c2c69abe1988/packages/core/src/i18n/translations).

The following image is an example of how the pagination component looks when the translation text returns as undefined.

![Image](https://github.com/user-attachments/assets/80be8a19-87aa-4980-88c3-9ce86044f13a)

Translation files appear to be bundled in the web-components.entry.js file.
https://dev.va.gov/generated/web-components.entry.js

For testing it is recommended that `yarn export` is ran locally to generate static html pages.
These pages in theory should display similarly to what we are seeing in dev. Testing locally using `yarn dev` will show the component working. 

Potential areas to check
- Data race
- Dependency issue

## Acceptance Criteria
- [ ] Components using i18next show their translated text in static generated pages.

**Comment by ttran-Therisa** [comment]
This is the relating PR: https://github.com/department-of-veterans-affairs/next-build/pull/611

The PR includes:

- Moving the adding web components in the _document.tsx higher in the file for initialization and loading. 
- Updated pressReleaseTeaser, newsStoryTeaser, and contentFooter to implement the va components <va-link> and <va-button>
