### ISSUE TITLE
[Launch] Lincoln quote needed in the comments

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#640]
## Description

VA mission statement needs to be present when a user inspects the page.
We need to add the following comment below the footer
``

## Additional Notes

There is a utility in next-build that can be used to achieve this.
`<HTMLComment position="head" content={comment} />`

## Acceptance Criteria

- [ ] Quote is visible on all pages below the footer.

**Comment by ttran-Therisa** [comment]
Install Htmlcomment from yarn add react-html-comment to inject the VA mission comment and added the div logout-modal-root to match prod
