### ISSUE TITLE
[Launch] Next Build Footer Markup

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#646]
## Description

Footer markup in Next Build does not match the current footer markup in production.

The footer markup should match the below

<details>
<summary>Footer HTML Markup</summary>
`<footer class="footer">
  <div id="footerNav" data-minimal-footer="false"><div><div class="footer-inner"><div aria-hidden="false" class="usa-grid-full flex-container usa-grid-flex-mobile va-footer-content"><div class="va-footer-linkgroup"><h2 class="va-footer-linkgroup-title">Veteran programs and services</h2><ul class="va-footer-links"><li><a href="https://www.va.gov/homeless/">Homeless Veterans</a></li><li><a href="https://www.va.gov/womenvet/">Women Veterans</a></li><li><a href="https://www.va.gov/centerforminorityveterans/">Minority Veterans</a></li><li><a href="https://www.patientcare.va.gov/lgbt/">LGBTQ+ Veterans</a></li><li><a href="https://www.ptsd.va.gov/">PTSD</a></li><li><a href="https://www.mentalhealth.va.gov/">Mental health</a></li><li><a href="https://department.va.gov/veteran-sports/">Adaptive sports and special events</a></li><li><a href="https://www.va.gov/outreach-and-events/events/">VA outreach events</a></li><li><a href="https://www.nrd.gov/">National Resource Directory</a></li></ul></div><div class="va-footer-linkgroup" id="footer-services"><h2 class="va-footer-linkgroup-title">More VA resources</h2><ul class="va-footer-links"><li><a href="https://www.va.gov/find-forms/">VA forms</a></li><li><a href="https://www.accesstocare.va.gov/">VA health care access and quality</a></li><li><a href="https://www.va.gov/get-help-from-accredited-representative">Get help from an accredited representative or VSO</a></li><li><a href="https://www.mobile.va.gov/appstore/">VA mobile apps</a></li><li><a href="https://department.va.gov/about/state-departments-of-veterans-affairs-office-locations/">State Veterans Affairs offices</a></li><li><a href="https://www.va.gov/opal/fo/dbwva.asp">Doing business with VA</a></li><li><a href="https://www.va.gov/jobs/">Careers at VA</a></li><li><a href="https://www.va.gov/outreach-and-events/outreach-materials">VA outreach materials</a></li><li><a href="https://www.va.gov/welcome-kit/">Your VA welcome kit</a></li></ul></div><div class="va-footer-linkgroup" id="footer-popular"><h2 class="va-footer-linkgroup-title">Get VA updates</h2><ul class="va-footer-links"><li><a href="https://news.va.gov/">VA news</a></li><li><a href="https://www.va.gov/opa/pressrel/">Press releases</a></li><li><a href="https://public.govdelivery.com/accounts/USVA/subscriber/new/">Email updates</a></li><li><a href="https://www.facebook.com/VeteransAffairs">Facebook</a></li><li><a href="https://www.instagram.com/deptvetaffairs/">Instagram</a></li><li><a href="https://www.twitter.com/DeptVetAffairs/">Twitter</a></li><li><a href="https://www.flickr.com/photos/VeteransAffairs/">Flickr</a></li><li><a href="https://www.youtube.com/user/DeptVetAffairs">YouTube</a></li><li><a href="https://digital.va.gov/web-governance/social-media/social-media-sites/">All VA social media</a></li></ul></div><div class="va-footer-linkgroup" id="veteran-crisis"><h2 class="va-footer-linkgroup-title">In crisis? Talk to someone now</h2><ul class="va-footer-links"><li><button class="va-button-link va-overlay-trigger" data-show="#modal-crisisline">Veterans Crisis Line</button></li></ul><h2 class="va-footer-linkgroup-title vads-u-margin-top--2 vads-u-padding-bottom--1">Get answers</h2><ul class="va-footer-links"><li><a href="https://www.va.gov/resources/">Resources and support</a></li><li><a href="https://www.va.gov/contact-us/">Contact us</a></li><li><h2 class="va-footer-linkgroup-title vads-u-margin-top--2 vads-u-padding-bottom--1">Call us</h2><a href="tel:18006982411">800-698-2411</a></li><li><a aria-label="TTY: 7 1 1." href="tel:+1711">TTY: 711</a></li><li><h2 class="va-footer-linkgroup-title vads-u-margin-top--2 vads-u-padding-bottom--1">Visit a medical center or regional office</h2><a href="https://www.va.gov/find-locations/">Find a VA location</a></li></ul></div></div><div aria-hidden="true" class="usa-grid-full flex-container usa-grid-flex-mobile va-footer-content"><ul class="usa-accordion va-footer-accordion"><li><div class="vads-u-background-color--secondary-darkest vads-u-display--flex vads-u-flex-direction--row vads-u-align-items--center vads-u-justify-content--center vads-u-text-align--center vads-u-padding--0p5"><button class="va-button-link vads-u-color--white vads-u-text-decoration--none va-overlay-trigger" data-show="#modal-crisisline" id="footer-crisis-line"><span>Talk to the <strong>Veterans Crisis Line</strong> now</span><svg aria-hidden="true" class="vads-u-margin-left--1" focusable="false" width="16" viewBox="7 1 17 17" xmlns="http://www.w3.org/2000/svg"><path fill="#fff" fill-rule="evenodd" clip-rule="evenodd" d="M9.99997 6L8.58997 7.41L13.17 12L8.58997 16.59L9.99997 18L16 12L9.99997 6Z"></path></svg></button></div></li><li><button class="usa-button-unstyled usa-accordion-button va-footer-button" aria-controls="veteran-contact" itemprop="name" aria-expanded="false">Contact us</button><div class="usa-accordion-content va-footer-accordion-content" id="veteran-contact" aria-hidden="true"><h2 class="va-footer-linkgroup-title vads-u-padding-bottom--1">Get answers</h2><ul class="va-footer-links"><li><a href="https://www.va.gov/resources/">Resources and support</a></li><li><a href="https://www.va.gov/contact-us/">Contact us</a></li><li><h2 class="va-footer-linkgroup-title vads-u-margin-top--2 vads-u-padding-bottom--1">Call us</h2><a href="tel:18006982411">800-698-2411</a></li><li><a aria-label="TTY: 7 1 1." href="tel:+1711">TTY: 711</a></li><li><h2 class="va-footer-linkgroup-title vads-u-margin-top--2 vads-u-padding-bottom--1">Visit a medical center or regional office</h2><a href="https://www.va.gov/find-locations/">Find a VA location</a></li></ul></div></li><li><button class="usa-button-unstyled usa-accordion-button va-footer-button" aria-controls="footer-veteran-programs" itemprop="name" aria-expanded="false">Veteran programs and services</button><div class="usa-accordion-content va-footer-accordion-content" aria-hidden="true" id="footer-veteran-programs"><ul class="va-footer-links"><li><a href="https://www.va.gov/homeless/">Homeless Veterans</a></li><li><a href="https://www.va.gov/womenvet/">Women Veterans</a></li><li><a href="https://www.va.gov/centerforminorityveterans/">Minority Veterans</a></li><li><a href="https://www.patientcare.va.gov/lgbt/">LGBTQ+ Veterans</a></li><li><a href="https://www.ptsd.va.gov/">PTSD</a></li><li><a href="https://www.mentalhealth.va.gov/">Mental health</a></li><li><a href="https://department.va.gov/veteran-sports/">Adaptive sports and special events</a></li><li><a href="https://www.va.gov/outreach-and-events/events/">VA outreach events</a></li><li><a href="https://www.nrd.gov/">National Resource Directory</a></li></ul></div></li><li><button class="usa-button-unstyled usa-accordion-button va-footer-button" aria-controls="veteran-resources" itemprop="name" aria-expanded="false">More VA resources</button><div class="usa-accordion-content va-footer-accordion-content" aria-hidden="true" id="veteran-resources"><ul class="va-footer-links"><li><a href="https://www.va.gov/find-forms/">VA forms</a></li><li><a href="https://www.accesstocare.va.gov/">VA health care access and quality</a></li><li><a href="https://www.va.gov/get-help-from-accredited-representative">Get help from an accredited representative or VSO</a></li><li><a href="https://www.mobile.va.gov/appstore/">VA mobile apps</a></li><li><a href="https://department.va.gov/about/state-departments-of-veterans-affairs-office-locations/">State Veterans Affairs offices</a></li><li><a href="https://www.va.gov/opal/fo/dbwva.asp">Doing business with VA</a></li><li><a href="https://www.va.gov/jobs/">Careers at VA</a></li><li><a href="https://www.va.gov/outreach-and-events/outreach-materials">VA outreach materials</a></li><li><a href="https://www.va.gov/welcome-kit/">Your VA welcome kit</a></li></ul></div></li><li><button class="usa-button-unstyled usa-accordion-button va-footer-button" aria-controls="veteran-connect" itemprop="name" aria-expanded="false">Get VA updates</button><div class="usa-accordion-content va-footer-accordion-content" id="veteran-connect" aria-hidden="true"><ul class="va-footer-links"><li><a href="https://news.va.gov/">VA news</a></li><li><a href="https://www.va.gov/opa/pressrel/">Press releases</a></li><li><a href="https://public.govdelivery.com/accounts/USVA/subscriber/new/">Email updates</a></li><li><a href="https://www.facebook.com/VeteransAffairs">Facebook</a></li><li><a href="https://www.instagram.com/deptvetaffairs/">Instagram</a></li><li><a href="https://www.twitter.com/DeptVetAffairs/">Twitter</a></li><li><a href="https://www.flickr.com/photos/VeteransAffairs/">Flickr</a></li><li><a href="https://www.youtube.com/user/DeptVetAffairs">YouTube</a></li><li><a href="https://digital.va.gov/web-governance/social-media/social-media-sites/">All VA social media</a></li></ul></div></li><li><h2 class="va-footer-linkgroup-title"><button class="usa-button-unstyled usa-accordion-button va-footer-button" aria-controls="veteran-language-support" itemprop="name" aria-expanded="false">Language assistance</button></h2><div class="usa-accordion-content va-footer-accordion-content vads-u-padding-bottom--0 vads-u-padding-left--0p5" id="veteran-language-support" aria-hidden="true"><div class="usa-grid usa-grid-full va-footer-links-bottom"><ul class="vads-u-margin-top--0 vads-u-margin-bottom--0 vads-u-padding-bottom--0"><li><a href="https://www.va.gov/asistencia-y-recursos-en-espanol" lang="es" hreflang="es"> Español</a></li><li><a href="https://www.va.gov/tagalog-wika-mapagkukunan-at-tulong" lang="tl" hreflang="tl"> Tagalog</a></li><li><a href="https://www.va.gov/resources/how-to-get-free-language-assistance-from-va/" lang="en" hreflang="en"> Other languages</a></li></ul></div></div></li></ul></div><div class="usa-grid usa-grid-full va-footer-links-bottom vads-u-border-color--white vads-u-border-bottom--1px vads-u-border-top--1px vads-u-padding-top--2 vads-u-padding-bottom--1p5 vads-u-padding-left--0"><h2 class="va-footer-linkgroup-title vads-u-padding-bottom--1">Language assistance</h2><ul class="vads-u-margin-top--0 vads-u-margin-bottom--0 vads-u-padding-bottom--0"><li><a href="https://www.va.gov/asistencia-y-recursos-en-espanol" lang="es" hreflang="es"> Español</a></li><li><a href="https://www.va.gov/tagalog-wika-mapagkukunan-at-tulong" lang="tl" hreflang="tl"> Tagalog</a></li><li><a href="https://www.va.gov/resources/how-to-get-free-language-assistance-from-va/" lang="en" hreflang="en"> Other languages</a></li></ul></div><div class="usa-grid usa-grid-full footer-banner"><a href="/" title="Go to VA.gov"><img src="https://www.va.gov/img/homepage/va-logo-white.png" alt="VA logo and Seal, U.S. Department of Veterans Affairs" width="200" class="vads-u-height--auto"></a></div><div class="usa-grid usa-grid-full va-footer-links-bottom"><ul><li><a href="https://www.va.gov/accessibility-at-va">Accessibility</a></li><li><a href="https://www.va.gov/resources/your-civil-rights-and-how-to-file-a-discrimination-complaint/">Civil Rights</a></li><li><a href="https://department.va.gov/foia/">Freedom of Information Act (FOIA)</a></li><li><a href="https://www.va.gov/report-harassment/">Harassment</a></li><li><a href="https://www.va.gov/oig/">Office of Inspector General</a></li><li><a href="https://www.va.gov/opa/Plain_Language.asp">Plain language</a></li><li><a href="https://www.va.gov/privacy-policy/">Privacy, policies, and legal information</a></li><li><a href="https://www.oprm.va.gov/">VA Privacy Service</a></li><li><a href="https://www.va.gov/ormdi/NOFEAR_Select.asp">No FEAR Act Data</a></li><li><a href="https://www.usa.gov/">USA.gov</a></li><li><a href="https://www.va.gov/performance-dashboard/">VA performance dashboard</a></li><li><a href="https://www.va.gov/veterans-portrait-project/">Veterans Portrait Project</a></li></ul></div></div><div id="modal-crisisline" class="va-overlay va-modal va-modal-large" role="alertdialog"><div class="va-crisis-panel va-modal-inner"><button aria-label="Close this modal" class="va-modal-close va-overlay-close va-crisis-panel-close" type="button"><svg aria-hidden="true" class="va-overlay-close" focusable="false" id="close-button-icon" viewBox="2 2 20 20" width="30" xmlns="http://www.w3.org/2000/svg"><path fill="#005ea2" d="m8.4 17 3.6-3.6 3.6 3.6 1.4-1.4-3.6-3.6L17 8.4 15.6 7 12 10.6 8.4 7 7 8.4l3.6 3.6L7 15.6 8.4 17Zm3.6 5a10.1 10.1 0 0 1-9.21-6.1A9.74 9.74 0 0 1 2 12a10.1 10.1 0 0 1 6.1-9.21A9.74 9.74 0 0 1 12 2a10.1 10.1 0 0 1 9.21 6.1c.53 1.22.79 2.52.79 3.9s-.26 2.68-.79 3.9a10.1 10.1 0 0 1-5.31 5.31A9.74 9.74 0 0 1 12 22Z"></path></svg></button><div class="va-overlay-body va-crisis-panel-body"><h3 class="va-crisis-panel-title">We’re here anytime, day or night – 24/7</h3><p>If you are a Veteran in crisis or concerned about one, connect with our caring, qualified responders for confidential help. Many of them are Veterans themselves.</p><ul class="va-crisis-panel-list"><li><svg aria-hidden="true" class="va-crisis-panel-icon" focusable="false" viewBox="0 0 23 23" width="26" xmlns="http://www.w3.org/2000/svg" style="transform: rotate(270deg);"><path fill="#000" fill-rule="evenodd" clip-rule="evenodd" d="M6.62 10.79C8.06 13.62 10.38 15.93 13.21 17.38L15.41 15.18C15.68 14.91 16.08 14.82 16.43 14.94C17.55 15.31 18.76 15.51 20 15.51C20.55 15.51 21 15.96 21 16.51V20C21 20.55 20.55 21 20 21C10.61 21 3 13.39 3 4C3 3.45 3.45 3 4 3H7.5C8.05 3 8.5 3.45 8.5 4C8.5 5.25 8.7 6.45 9.07 7.57C9.18 7.92 9.1 8.31 8.82 8.59L6.62 10.79Z"></path></svg><a href="tel:988">Call <strong>988 and select 1</strong></a></li><li><svg aria-hidden="true" class="va-crisis-panel-icon" focusable="false" viewBox="0 0 24 24" width="16" xmlns="http://www.w3.org/2000/svg"><path fill="#000" d="M15.5 1h-8A2.5 2.5 0 0 0 5 3.5v17A2.5 2.5 0 0 0 7.5 23h8a2.5 2.5 0 0 0 2.5-2.5v-17A2.5 2.5 0 0 0 15.5 1Zm-4 21a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm4.5-4H7V4h9v14Z"></path></svg><a href="sms:838255">Text <strong>838255</strong></a></li><li><svg aria-hidden="true" class="va-crisis-panel-icon" focusable="false" viewBox="0 0 24 24" width="16" xmlns="http://www.w3.org/2000/svg"><path fill="#000" fill-rule="evenodd" clip-rule="evenodd" d="M21 6H19V15H6V17C6 17.55 6.45 18 7 18H18L22 22V7C22 6.45 21.55 6 21 6ZM17 12V3C17 2.45 16.55 2 16 2H3C2.45 2 2 2.45 2 3V17L6 13H16C16.55 13 17 12.55 17 12Z"></path></svg><a class="no-external-icon" href="https://www.veteranscrisisline.net/get-help-now/chat/">Start a confidential chat</a></li><li><svg aria-hidden="true" class="va-crisis-panel-icon" focusable="false" viewBox="0 0 24 24" width="16" xmlns="http://www.w3.org/2000/svg"><path fill="#1B1B1B" fill-rule="evenodd" d="m20.51 22-6.79-6.79c-.34.28-.62.52-.86.75-.24.22-.44.45-.6.7a6.72 6.72 0 0 0-.48.8 11.8 11.8 0 0 0-.44 1.03c-.31.81-.8 1.45-1.45 1.9a3.84 3.84 0 0 1-2.25.7 3.3 3.3 0 0 1-2.36-.95 3.52 3.52 0 0 1-1.1-2.34h1.38a2.19 2.19 0 0 0 .7 1.37 2 2 0 0 0 1.38.54c.55 0 1.04-.18 1.46-.52a3.9 3.9 0 0 0 1.07-1.55 11.2 11.2 0 0 1 1.1-2c.21-.27.44-.53.67-.76a8.24 8.24 0 0 1 .77-.68L5.83 7.32a6.64 6.64 0 0 0-.2.72 5.16 5.16 0 0 0-.1.77H4.16a8.29 8.29 0 0 1 .2-1.33c.1-.43.23-.83.41-1.21L2 3.49l.99-.99 18.5 18.51-.98.99Zm-2.32-6.26-.98-.99a8.6 8.6 0 0 0 1.56-2.7A9.05 9.05 0 0 0 19.29 9c0-1.17-.2-2.28-.6-3.33a7.82 7.82 0 0 0-1.78-2.74L17.94 2a9.5 9.5 0 0 1 2.02 3.17 10.4 10.4 0 0 1 .08 7.4 10.5 10.5 0 0 1-1.85 3.17Zm-2.52-2.52-1.05-1.06a5.57 5.57 0 0 0 .78-3.07c0-1.38-.47-2.54-1.4-3.48a4.68 4.68 0 0 0-3.47-1.4c-.56 0-1.1.07-1.6.22a5.16 5.16 0 0 0-1.38.67l-.99-.99a6.34 6.34 0 0 1 1.84-.95 6.77 6.77 0 0 1 2.13-.33c1.84 0 3.34.58 4.5 1.75a6.12 6.12 0 0 1 1.74 4.5 9.3 9.3 0 0 1-.26 2.29 6.03 6.03 0 0 1-.84 1.85ZM12.46 10 9.59 7.14a2.24 2.24 0 0 1 .46-.17 2.02 2.02 0 0 1 2 .58 2.2 2.2 0 0 1 .41 2.45Zm-1.97 1.21c-.6 0-1.1-.2-1.52-.62a2.06 2.06 0 0 1-.62-1.51 2.27 2.27 0 0 1 .23-.99l2.9 2.9a2.27 2.27 0 0 1-1 .22Z" clip-rule="evenodd"></path></svg><p><a href="tel:711" aria-label="7 1 1">For TTY, call <strong>711 then 988</strong></a></p></li></ul>Get more resources at <a class="no-external-icon" href="https://www.veteranscrisisline.net/">VeteransCrisisLine.net</a>.</div></div></div></div></div>
</footer>`
</details>

## Additional Notes

N/A

## Acceptance Criteria

- [ ] Footer updated to match production

**Comment by ttran-Therisa** [comment]
Removed the wrapping contentinfo section and the div announcement-root
