### ISSUE TITLE
[Launch] Next Build Promos not rendering

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#647]
## Description

Promo banners do not appear to be showing in the Mega Nav.

Example of next-build
![Image](https://github.com/user-attachments/assets/49b6ca32-b4f1-4166-a857-26730400d3c9)

Example of production
![Image](https://github.com/user-attachments/assets/d237b126-734c-4c06-9fb3-fcb79f9229f4)

## Acceptance Criteria

- [ ] Promo banners show in the mega nav

**Comment by ttran-Therisa** [comment]
This wasn't an issue with the codebase. The Drupal Dev did not set all the promos to the relating menu sections. I went in https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/admin/structure/menu/manage/header-megamenu?check_logged_in=1 and updated the sub-sections under "VA Benefit and Health Care" missing their correlating promos.

**Comment by mreed101** [comment]
Confirmed as a data issue. Closing this ticket

**Comment by randimays** [comment]
I'm seeing this issue in dev; none of the promos appear. CC @ttran-Therisa @mreed101 

<img width="600" src="https://github.com/user-attachments/assets/050053e6-6180-4044-b619-52b24a1a3651" />
