### ISSUE TITLE
[Launch] Next Build Maintenance Banner

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#648]
## Description

We need to confirm that the maintenance banner is working in next-build as it currently is not showing as an empty container on the page.

Production left, Next Build right

![Image](https://github.com/user-attachments/assets/7dc4859c-b188-4f29-9412-db95b4098739)

## Acceptance Criteria

- [ ] Maintenance banner works as expected

**Comment by timcosgrove** [comment]
It is enough here to drop in the div that handles this on [Content Build, found here](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/components/banners.drupal.liquid#L20):
```
<!-- Maintenance banner -->
<div
  aria-label="Maintenance banner"
  data-widget-type="maintenance-banner"
  role="region"
></div>
```

This should be dropped into `<Wrapper />` either directly or better as its own component.

**Comment by ttran-Therisa** [comment]
relating [PR](https://github.com/department-of-veterans-affairs/next-build/issues/648).
