### ISSUE TITLE
[Launch] Next Build Analytics

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#656]
## Description

There has been a switch to GA4 tracking which is different than what was previously done in Next Build.
All tracking needs to be updated to mimic the work that was done in Content Build.

The following pieces are crucial to us having accurate tracking
- GTM code should be present on all pages. (each environment has a different auth and preview that needs to be set in the proper .env)
- The DAP script (in supporting details) should be on all pages 
- Each time a user goes to a va.gov page we should be able to see a page_view event fire
- All internal links should track as a nav-link-click (this will happen as long as the links use the va-link component)

## Additional Notes

Most of this work seemed to be done at the component level but we need to verify that items are tracking as expected. Contact Randi Mays to discuss what frontend work was done. There are chrome extensions that will allow you to see what data is being sent via google analytics.

## Supporting Details

This [document](https://docs.google.com/document/d/1DysO9vpWgAdpDXX3c6SChfZLtYRXd0-mStv0pxopgfY/edit) contains the ids that need to be modified per environment

Below is the DAP script that needs to be on next-build pages
```
<script async type="text/javascript" nonce="DueDILCmFR41JQe9LmVZVpXR7BI44zvA" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=VA" id="_fed_an_ua_tag"></script>
```

A good way to test tracking is to use [Adswerve](https://chromewebstore.google.com/detail/adswerve-datalayer-inspec/kmcbdogdandhihllalknlcjfpdjcleom?pli=1). On chrome go to your settings in the dev inspector and turn on preserve logs under the network setting. Do not turn on any advance feature of Adswereve.

<img width="557" alt="Screenshot 2024-09-06 at 12 27 13 AM" src="https://github.com/user-attachments/assets/bf8bac64-26fb-4a6e-a529-a6252cef9fa8">

## Acceptance Criteria

- [x] GTM tracking is implemented and using the proper environment variables
- [x] DAP script is on the page
- [x] page_view fires when a user views a page
- [x] Links track as nav-link-click

**Comment by ttran-Therisa** [comment]
Following steps 

1. For any template with recordEvent, look at its equivalent in content-build
2. check that equivalent for any recent updates, with an eye for changes relating to analytics</head>

<html>
<head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>


  Content File / Next File / Same | Content-Build | Next-Build | Last changed for  content-build
-- | -- | -- | --
PressRelease | `<va-link>` | `<a>` with recordEvent | 1 month - Randi   Mays
Event | `<va-link>` | `<va-link>` with recordEvent | 3 months - Randi   Mays
News_story / StoryListingLink | `<va-link>` | `<a> `with recordEvent | 3 months - Josh   Mills
How_do_you_rate / rateYourExperience | Conditional  RecordEvent | Conditional  RecordEvent | 3 years - Kelson   Adams
linkTeaser | Two `<va-link>` | Two `<li>` with recordEvent | 6 months - Randi   Mays, Chris Kim
imageAndStaticMap | `<div>` with  recordEvent | `<div>` with  recordEvent | 3 years - Napoleon   K
Default_contact / contactInfo | `<a>` with recordEvent | `<Link>`  with recordEvent | 1 Year - Randi   Mays
benefitHubsLinks | `<va-link>` | `<a>`  with recordEvent> | 6 months - Randi   Mays
Fullwidth_banner_alerts / facilitybanner | `<va-link>` with  recordEvent> | Conditional  RecordEvent | 3 months - Randi   Mays
404.tsx |  Not Found  | useEffect w/   record Event |  N/A



</div>


</body>

</html>

**Comment by ttran-Therisa** [comment]
Using Adswerve and [Content-Build PR](https://github.com/department-of-veterans-affairs/content-build/pull/2217) as reference to test if the Google Analytics is working and no duplications. 
## Testing done on dev.va.gov

### Replicate Testing in Content-Build's PR
---
#### Disability compensation accordion: "Learn how to manage disability compensation benefits online" 
`Matched Prod`

<details>
<summary>Expand Image</summary>
![Screenshot 2024-09-04 at 12 51 31 PM](https://github.com/user-attachments/assets/013ac097-f65f-4798-bf5e-47d488d0e46f)

</details>

**Comment by ttran-Therisa** [comment]
Rank of fixing
1. rateYourExperience [ fix dev to send the page-view like prod ]
3. Fullwdith_banner_alerts /facilityBanner [ Update dev to be a nav-link-click and not a nav-alert-boc-link-click ]
4. News_story /storyListingLink [ Update to va-link ]
5. pressRelease [ Update to va-link ]
6. (Maybe) ImageAnStaticMap [ Possibly don't change since they both are behaving the same ]
