### ISSUE TITLE
Next Build Feedback Section Styling

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#659]
## Description

Feedback section styling for events needs to be update to match production.

 - Padding of the horizontal line to the Feedback button floated div is 15px in prod and 22px in dev
 - Padding to the left of the feedback button in prod is 376px and 689px in dev
 - Padding to the top of the feedback button is 5px in prod and 8px in dev
 - Padding to the bottom of the feedback button is 10px and 14px in dev
 - Padding to the right of the feedback button in prod is 0px and 8px in dev
 - Prod has a max width that is missing on AP because the usa-content class is not being used so this section is full width

## Additional Notes

This section is using some custom styles that might be difficult to replicate exactly. We also would like to avoid custom code whenever possible. Try using the following classes to acheive the desired styling.
class="usa-content vads-u-border-top--2px vads-u-border-color--gray-light vads-u-padding-y--2"

## Screenshots

https://drive.google.com/file/d/1kwy24po1b_TKmCvfn6QIXFI8ysbm0wnv/view?usp=sharing

Screenshots of what this would look like with the proposed classes (see additional notes column)
- https://drive.google.com/file/d/1ShqYk2-ufqo1ijtDa_vc0kD7kP-XNdCn/view?usp=sharing
- https://drive.google.com/file/d/1koXA-PIxcu1XRBBhdcrp2bbZKpjOllU1/view?usp=sharing
- https://drive.google.com/file/d/133rA3k7wCzdfSArxOmtPEQxRZhpzKaMr/view?usp=sharing

## Acceptance Criteria

- [ ] Feedback styling is updated to match production

**Comment by ttran-Therisa** [comment]
relating [PR](https://github.com/department-of-veterans-affairs/next-build/pull/679)
