### ISSUE TITLE
Next Build Event Image Margin

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#660]
## Description

Next Build event image is missing classes that are being applied in production.
The image is missing all the VADS margin classes in which makes it become too close to the text below.

## Screenshots

https://drive.google.com/file/d/1LEItTPY0jv0hCRdl0g_vas7IkywVPIaz/view?usp=sharing

## Acceptance Criteria

- [ ] VADS classes added to the Event image

**Comment by nfpappas-oddball** [comment]
Need Clarification. I am seeing matching classes in the html that is inconsistent with the documented screenshot. My screenshot is below. Please re-test

![image](https://github.com/user-attachments/assets/4d5d7cb6-1200-49b5-814a-fd5d41ac375e)
![image](https://github.com/user-attachments/assets/9dab9dcd-c1c0-4fc6-9ef2-a32d32864e4a)

**Comment by nfpappas-oddball** [comment]
![image](https://github.com/user-attachments/assets/f9544242-08ba-4896-8693-e8929bc1c38e)
