### ISSUE TITLE
Next Build Intro Text Styling

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#661]
## Description

On the events page the <p> tag for the intro text is missing the vads-u-margin-top--0 class that is in production.
This class needs to be added to that tag so that the spacing between the H1 and the p tag mimic what is in prod.

## Acceptance Criteria

- [ ] Intro text class is updated

**Comment by nfpappas-oddball** [comment]
Having trouble finding the issue and need clarification. 

in prod i see:

**Comment by ttran-Therisa** [comment]
Working on this now to add with ticket https://github.com/department-of-veterans-affairs/next-build/issues/667 since they involve the same event layout

**Comment by ttran-Therisa** [comment]
relating [PR](https://github.com/department-of-veterans-affairs/next-build/pull/701)
