### ISSUE TITLE
Next Build Social Share styling

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#662]
## Description

On the event page we need to update the styling of the links to match what is in production.
- The VADS margin class on Cost should be 1 instead of 2. This causes the spacing to be too big between this and whatever item is below
- On social links in prod there is no padding to the right, in dev there is 20px of padding to the right. Remove class "medium-screen:vads-u-margin-right--2p5"
- Padding between icon and link in prod is 7px and 4px in dev
- Space between X link and Register link is too small

## Acceptance Criteria

- [ ] Social links styling updated to match production

**Comment by ttran-Therisa** [comment]
relating [PR](https://github.com/department-of-veterans-affairs/next-build/pull/701)
