### ISSUE TITLE
Next Build Register Link missing for past events

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#668]
## Description

On event pages the user is not able to register for events that have already passed.
We need to determine if this is the correct business logic and update it accordingly

## Acceptance Criteria

- [ ] TBD

**Comment by aklausmeier** [comment]
@mreed101 We can close this ticket as a non-op, Sitewide intends to [hide past events from the FE](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9474).
