### ISSUE TITLE
Next Build Reverse Proxy Test Plan

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#694]
## Description

Reverse proxy needs a thorough test plan before attempting to release to production. We need a detailed plan of how changes will be tested and the order they will follow as they move through different environments. 

This plan will need to include

- Objectives, Scope, Acceptance Criteria, Deliverables, Roles & Responsibilities, Risk Assessment and Outcomes
- Regression testing of site functionality for va.gov
- List of test cases that will be used (exact steps to be followed)
- Testing schedule and a process to inform teams of impeding test
- Detailed breakdown of how changes will be tested on dev, staging, production and locally
- A detailed post launch fallback strategy

## Supporting details

JR Reed and Tim Cosgrove will be your point of contacts for any questions you may have.

## Acceptance Criteria

- [ ] Artifact created and shared with VA & Platform Engineering teams
- [ ] Approval of test plan by VA & Platform Engineering

**Comment by gracekretschmer-metrostar** [comment]
Link to postmortem for context: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3393782221/Draft+Postmortem+8+20+2024+Reverse+Proxy+change+causing+Outage+to+Va.gov+Homepage

**Comment by keisterj-oddball** [comment]
Test plan is documented here: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3426189323/AP+Reverse+Proxy+Test+Plan
