### ISSUE TITLE
[AP] Build content guide for Next Build

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#711]
## Description

Next Build currently contains extensive documentation but it can be difficult for developers to quickly digest and find critical information. To improve this we propose creating a comprehensive ReadMe or GitHub Wiki page that provides a clear and concise guide to get developers up and running with the next-build project.

- Indexing Existing Documentation: Ensure that all relevant documentation within the repository is represented in this index file, making it easier to navigate.
- Section: Include a Frequently Asked Questions (FAQ) section to help developers quickly find solutions to common issues.
- Focus on Developer Onboarding and Issue Tracking: The main objective is to help developers quickly locate critical information necessary to maintain the application and provide clear steps for troubleshooting and resolving issues.

This documentation will serve as a resource for both new and existing developers, streamlining their workflow and reducing the time spent searching for solutions.

## Acceptance Criteria

- [ ] Content guide created

**Comment by nfpappas-oddball** [comment]
Started an index page. Mostly just modified the default readme to be this page. code is on branch origin/next_index_documentation

**Comment by jcbolling** [comment]
This ticket moved into Sprint 16 to allow time to meet with Nick so he could review the common issues identified by the rest of the team and provide his feedback. Nick and I met yesterday and reviewed the document.
