### ISSUE TITLE
[AP] Datadog Synthetic Monitor

### ISSUE THREAD

**Issue by mreed101** [department-of-veterans-affairs/next-build#724]
## Description

In order to test changes to reverse proxy, we will need a datadog synthetic monitors setup to test if the homepage is displayed.
There will also need to be another monitor that simulates a 404 to ensure the error page from content build is displayed.

## Acceptance Criteria

- [ ] Create a datadog synthetic monitor (HTTP) that asserts that [va.gov](http://va.gov/) is accessible
- [ ] Create a datadog synthetic monitor (HTTP) that asserts the 404 behavior on [va.gov](http://va.gov/)

**Comment by LisaLindsey** [comment]
@mreed101 please review this ticket, has it fully met DoD requirements?

**Comment by jcbolling** [comment]
The monitor in question can be found at https://vagov.ddog-gov.com/monitors/277210. @mreed101 can you please review this and give your blessing to close the issue? Thank you so much!

**Comment by mreed101** [comment]
LGTM. Closing this ticket
