### ISSUE TITLE
Trigger production content release from CMS for certain events

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/next-build#749]
## Description
When certain content types are saved in the CMS, they trigger a Content Build content release, regardless of the time of day or day of the week. This is to allow certain timely content to reach va.gov quickly outside of the normal content release schedule.

Next Build should also follow this pattern so that timely content updates are posted quickly.

## Details
This functionality is handled by the CMS Drupal module va_gov_content_release: https://github.com/department-of-veterans-affairs/va.gov-cms/tree/main/docroot/modules/custom/va_gov_content_release

This will need to be augmented to handle Next Build content release in addition to Content Build.

**Comment by mreed101** [comment]
[Closing as this is related to](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16851)
